global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - booking-service:9191
          - payment-service:9292
          - seat-inventory-service:9393
